### ISSUE TITLE
Completing my program.

### ISSUE THREAD

**Issue by ajinkyaw** [nkolban/ESPLibs#1]
hi guys. 
(especially Neil Kolban sir) the tuts are really awesome. 

//VERY VERY SORRY FOR THE LACK OF ENGLISH. AND ALSO FOR NOT SHARING THE WHOLE CODE DUE TO DISCLOSURE ISSUES.

i have been trying to extend the GPIO pins of ESP8266-12E with PCF8574 . 
the problem i am facing here is i have successfully connected these both circuits and communication is also done. but the problem here i am facing is , when i send the signal to PCF8547 using write function it does turn off the led at that particular addressed pin , also when i select another pin or address it does the same , but at a time only one led is turning off , while switching another led the previous one also changes its state , it doesn't preserve. 

Simply when i change the led status , only that status is affecting others are getting reset to their values. 

here is my code guys :

      ' void setup() {
  
          Wire.begin(SDA_PIN,CLK_PIN);

       }

     void enlight(int cnt){
    
    if (cnt == 1) 
      value = value | 1<<cnt;
    if (cnt == 2) 
      value = value | 2<<cnt;
    if (cnt == 3) 
      value = value | 3<<cnt;
    if (cnt == 4) 
      value = value | 4<<cnt;
  
    value = ~value;
    
    Wire.begin(SDA_PIN,CLK_PIN);
    Wire.beginTransmission(0x20);
    Wire.write(value);
  
     Wire.endTransmission();
  
    
        }

      void loop() 
      {
  
        // Check if a client has connected
        WiFiClient client = server.available();
        if (!client) {
         return;
        }

       // Read the first line of the request
       String req = client.readStringUntil('\r');
        Serial.println(req);
       client.flush();

          // Match the request
             int val = -1; // We'll use 'val' to keep track of both the
                  // request type (read/set) and value if set

         // Otherwise request will be invalid. We'll say as much in HTML
    
    if(val == 12){
      
      if(LED1_STATUS == LOW){
        LED1_STATUS = HIGH;
        enlight(1);
      }else{
        LED1_STATUS = LOW;
        enlight(1);
      }
      s+= LED1_STATUS ;
      
      digitalWrite(LED1 ,LED1_STATUS );
      
      
    }else if(val == 13){
      
       if(LED2_STATUS == LOW){
        LED2_STATUS= HIGH;
        enlight(2);
       }else{
        LED2_STATUS= LOW;
        enlight(2);
       }
      s+= LED2_STATUS;
       
      digitalWrite(LED2,LED2_STATUS);  
       
      
    }else if(val == 14){
      
       if(LED3_STATUS== LOW){
        LED3_STATUS= HIGH;
         enlight(3);
       }else{
        LED3_STATUS= LOW;
         enlight(3);
       }
      s+= LED3_STATUS;
       
      digitalWrite(LED3,LED3_STATUS);  
     
      
    }else if(val == 16){
      
       if(LED4_STATUS== LOW){
        LED4_STATUS= HIGH;
         enlight(4);
       }else{
        LED4_STATUS= LOW;
         enlight(4);
       }
      s+= LED4_STATUS;
       
      digitalWrite(LED4,LED4_STATUS);  
       
      }
         client.print(s);
         client.flush();
      }

     void initHardware()
     {
       Serial.begin(115200);
       pinMode(LED1, OUTPUT);
       pinMode(LED2, OUTPUT);
       pinMode(LED3, OUTPUT);
       pinMode(LED4, OUTPUT);
  
       digitalWrite(LED1_STATUS, HIGH);
       digitalWrite(LED2_STATUS, HIGH);
       digitalWrite(LED3_STATUS, HIGH);
       digitalWrite(LED4_STATUS, HIGH);
 
    }`

**Comment by nkolban** [comment]
If I remember correctly, the PCF8574 takes an 8 bit value which is the value of ALL pins ... to be set.  So you should be setting the value of the desired output as a whole.

**Comment by ajinkyaw** [comment]
@nkolban  : sir , i have added one function to the code , which is enlight(); 
Apology for this but i am very very new to Electronics, up to What i have coded is understandable to me, i have learned up to that one. i am not be able to solve it is because of lack of knowledge in this subject.

does your comment means , that each pin has different 8 bit value. ??

**Comment by ajinkyaw** [comment]
found the solution..
